foldertest
/cluster/home/wlaumen/Euler/pypsa-eur/networks_redispatch/elec_s300_16_ec_lcopt_1H.nc
filepathtest
elec_s300_16_ec_lcopt_1H
Traceback (most recent call last):
  File "/cluster/home/wlaumen/.local/lib/python3.8/site-packages/xarray/backends/file_manager.py", line 199, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "/cluster/home/wlaumen/.local/lib/python3.8/site-packages/xarray/backends/lru_cache.py", line 53, in __getitem__
    value = self._cache[key]
KeyError: [<function _open_scipy_netcdf at 0x2b87f6641ee0>, ('/cluster/home/wlaumen/Euler/pypsa-eur/networks_redispatch/elec_s300_16_ec_lcopt_1H.nc',), 'r', (('mmap', None), ('version', 2))]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cluster/home/wlaumen/.local/lib/python3.8/site-packages/xarray/backends/scipy_.py", line 94, in _open_scipy_netcdf
    return scipy.io.netcdf_file(filename, mode=mode, mmap=mmap, version=version)
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/site-packages/scipy/io/netcdf.py", line 281, in __init__
    self._read()
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/site-packages/scipy/io/netcdf.py", line 602, in _read
    raise TypeError("Error: %s is not a valid NetCDF 3 file" %
TypeError: Error: /cluster/home/wlaumen/Euler/pypsa-eur/networks_redispatch/elec_s300_16_ec_lcopt_1H.nc is not a valid NetCDF 3 file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "solve_redispatch_networks.py", line 617, in <module>
    main()
  File "solve_redispatch_networks.py", line 614, in main
    solve_all_redispatch_workflows(c_rate=0.25, flex_share=0.1, flex_store=True)
  File "solve_redispatch_networks.py", line 584, in solve_all_redispatch_workflows
    n = pypsa.Network(path_n)
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/site-packages/pypsa/components.py", line 285, in __init__
    self.import_from_netcdf(import_name)
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/site-packages/pypsa/io.py", line 496, in import_from_netcdf
    with ImporterNetCDF(path=path) as importer:
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/site-packages/pypsa/io.py", line 200, in __init__
    self.ds = xr.open_dataset(path)
  File "/cluster/home/wlaumen/.local/lib/python3.8/site-packages/xarray/backends/api.py", line 557, in open_dataset
    ds = maybe_decode_store(store, chunks)
  File "/cluster/home/wlaumen/.local/lib/python3.8/site-packages/xarray/backends/api.py", line 453, in maybe_decode_store
    ds = conventions.decode_cf(
  File "/cluster/home/wlaumen/.local/lib/python3.8/site-packages/xarray/conventions.py", line 639, in decode_cf
    vars, attrs = obj.load()
  File "/cluster/home/wlaumen/.local/lib/python3.8/site-packages/xarray/backends/common.py", line 113, in load
    (_decode_variable_name(k), v) for k, v in self.get_variables().items()
  File "/cluster/home/wlaumen/.local/lib/python3.8/site-packages/xarray/backends/scipy_.py", line 166, in get_variables
    (k, self.open_store_variable(k, v)) for k, v in self.ds.variables.items()
  File "/cluster/home/wlaumen/.local/lib/python3.8/site-packages/xarray/backends/scipy_.py", line 155, in ds
    return self._manager.acquire()
  File "/cluster/home/wlaumen/.local/lib/python3.8/site-packages/xarray/backends/file_manager.py", line 181, in acquire
    file, _ = self._acquire_with_cache_info(needs_lock)
  File "/cluster/home/wlaumen/.local/lib/python3.8/site-packages/xarray/backends/file_manager.py", line 205, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "/cluster/home/wlaumen/.local/lib/python3.8/site-packages/xarray/backends/scipy_.py", line 105, in _open_scipy_netcdf
    raise TypeError(errmsg)
TypeError: Error: /cluster/home/wlaumen/Euler/pypsa-eur/networks_redispatch/elec_s300_16_ec_lcopt_1H.nc is not a valid NetCDF 3 file
            If this is a NetCDF4 file, you may need to install the
            netcdf4 library, e.g.,

            $ pip install netcdf4
            
